<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Creating-Arrays" data-toc-modified-id="Creating-Arrays-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Creating Arrays</a></span><ul class="toc-item"><li><span><a href="#1D-array" data-toc-modified-id="1D-array-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>1D array</a></span></li><li><span><a href="#2D-array" data-toc-modified-id="2D-array-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>2D array</a></span></li><li><span><a href="#3D-array" data-toc-modified-id="3D-array-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>3D array</a></span></li></ul></li><li><span><a href="#Initial-Placeholders" data-toc-modified-id="Initial-Placeholders-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Initial Placeholders</a></span><ul class="toc-item"><li><span><a href="#create-an-array-of-zeros" data-toc-modified-id="create-an-array-of-zeros-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>create an array of zeros</a></span></li><li><span><a href="#create-an-array-of-ones" data-toc-modified-id="create-an-array-of-ones-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>create an array of ones</a></span></li><li><span><a href="#Create-an-array-of-evenly-spaced-values-(step-value)" data-toc-modified-id="Create-an-array-of-evenly-spaced-values-(step-value)-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Create an array of evenly spaced values (step value)</a></span></li><li><span><a href="#Create-an-array-of-evenly-spaced-values-(number-of-samples)" data-toc-modified-id="Create-an-array-of-evenly-spaced-values-(number-of-samples)-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Create an array of evenly spaced values (number of samples)</a></span></li><li><span><a href="#Create-a-constant-array" data-toc-modified-id="Create-a-constant-array-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Create a constant array</a></span></li><li><span><a href="#Create-a-3X3-identity-matrix" data-toc-modified-id="Create-a-3X3-identity-matrix-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Create a 3X3 identity matrix</a></span></li><li><span><a href="#Create-an-array-with-random-values" data-toc-modified-id="Create-an-array-with-random-values-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Create an array with random values</a></span></li><li><span><a href="#Create-an-empty-array" data-toc-modified-id="Create-an-empty-array-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Create an empty array</a></span></li></ul></li><li><span><a href="#I/O" data-toc-modified-id="I/O-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>I/O</a></span><ul class="toc-item"><li><span><a href="#Saving-&amp;-Loading-On-Disk" data-toc-modified-id="Saving-&amp;-Loading-On-Disk-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Saving &amp; Loading On Disk</a></span></li></ul></li></ul></div>

### Creating Arrays


In [1]:
import numpy as np

#### 1D array

In [9]:
a = np.array([1,2,3])
a.ndim

1

#### 2D array

In [14]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b.ndim

2

In [13]:
# alternatively
b = np.array([[1.5,2,3],[4,5,6]])
b.ndim

2

#### 3D array

In [19]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
c.ndim

3

In [23]:
# alternatively
c = np.array([[[1.5,2,3],[4,5,6]], [[7,8,9],[4,8,9]]])
c.ndim

3

### Initial Placeholders

#### create an array of zeros

In [26]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

#### create an array of ones

In [29]:
a = np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Create an array of evenly spaced values (step value)

In [32]:
a =  np.arange(2,30,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### Create an array of evenly spaced values (number of samples)

In [35]:
a = np.linspace(0,2,9)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

#### Create a constant array

In [39]:
a = np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

#### Create a 3X3 identity matrix

In [41]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Create an array with random values

In [45]:
a = np.random.random(3)
a

array([0.37828375, 0.61453119, 0.33799851])

#### Create an empty array

In [48]:
a = np.empty([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

### I/O

#### Saving & Loading On Disk

In [49]:
a = np.array([2,3,4,5,8])
a
b = a.save()

array([2, 3, 4, 5, 8])