In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
m = np.array([[3, 4], [-1, 5]])

In [3]:
m

array([[ 3,  4],
       [-1,  5]])

In [4]:
m * m

array([[ 9, 16],
       [ 1, 25]])

In [5]:
A = np.array([[1, 3],
              [-8, 21]])
A

array([[ 1,  3],
       [-8, 21]])

In [6]:
B = np.array([[5, 2], 
              [1, 2]])
B

array([[5, 2],
       [1, 2]])

In [7]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

### Now, calculate 2I + 3A -AB

In [9]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 39.]])