#### Arange

In [1]:
import numpy as np

In [2]:
a = np.arange(25)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
a = np.arange(25).reshape(5, 5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
a[ :, 1: :2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [9]:
# return the last row
a[-1:, :]

array([[20, 21, 22, 23, 24]])

In [10]:
"""
return
5  7
15 17
"""

a[1::2, :4:2]

array([[ 5,  7],
       [15, 17]])