In [1]:
a = [1, 2, 3, 4, 5]
b = [11, 12, 13, 14, 15]
a + b

[1, 2, 3, 4, 5, 11, 12, 13, 14, 15]

In [2]:
result =  []

for i, j in zip(a, b):
    result.append(i+j)
    
result

[12, 14, 16, 18, 20]

In [3]:
import numpy as np

#### declaring arrays in numpy

In [5]:
a = np.array([1, 2, 3, 4])
type(a)

numpy.ndarray

#### Datatype

In [6]:
a.dtype

dtype('int32')

In [8]:
floating = np.array([1.1, 3.3, 4.4, 5.5])
floating.dtype

dtype('float64')

In [9]:
floating[0] = 2.2  # replace 1.1 with 2.2
floating 

array([2.2, 3.3, 4.4, 5.5])

#### Datatype must be same in the numpy array

In [22]:
dt = np.array([1, 11, 3, 4, 14])

In [23]:
dt

array([ 1, 11,  3,  4, 14])

In [24]:
dt[0] = 1.1  # avoids the decimal point 
dt

array([ 1, 11,  3,  4, 14])

#### Number of dimensions

In [25]:
dt.ndim

1

#### Shape

In [26]:
dt.shape 
# returns 5 as it has 5 elements (5, ) means it's vector (no column)
# for 2D array it will return (5,5) for 5 by 5 matrix

(5,)

#### Size or number of elements

In [27]:
dt.size # always returns an integer 

5

In [37]:
a

array([1, 2, 3, 4])

In [38]:
b = np.array([11.5, 15.5, 17.6, 19.5])

In [39]:
b

array([11.5, 15.5, 17.6, 19.5])

In [40]:
a + b # we can do this without any loop using NumPy

array([12.5, 17.5, 20.6, 23.5])

In [41]:
a/b

array([0.08695652, 0.12903226, 0.17045455, 0.20512821])

In [42]:
a * b

array([11.5, 31. , 52.8, 78. ])

In [43]:
a ** b

array([1.00000000e+00, 4.63409500e+04, 2.49651444e+08, 5.49755814e+11])

In [44]:
a

array([1, 2, 3, 4])

In [45]:
a * 10 # 10 is multiplied with each element

array([10, 20, 30, 40])

#### Universal Functions

In [46]:
  np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [50]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [51]:
b = a.copy()
b

array([1, 2, 3, 4])

In [52]:
b.fill(2)

In [53]:
b

array([2, 2, 2, 2])

In [54]:
a

array([1, 2, 3, 4])

#### Muti- Dimensional array

In [55]:
mda = np.array([[1, 2, 3], 
                [4, 5, 6]])

mda

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
mda.dtype

dtype('int32')

In [57]:
mda.shape

(2, 3)

In [58]:
mda.ndim  # number of dimension

2

In [59]:
mda.size  # The number of elements in the array

6

In [60]:
mda[0]  # row index 0 ( row 1)

array([1, 2, 3])

In [61]:
mda[1]  # row index 1 (row 2)

array([4, 5, 6])

In [62]:
mda[0][0]

1

In [63]:
mda

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
mda[1][0] # row 1, col 0

4