### Slicing

In [2]:
import numpy as np

In [3]:
a = np.array([10, 11, 12, 13])
a

array([10, 11, 12, 13])

a[:]

In [4]:
a[2:] # prints all index elements from 2 

array([12, 13])

In [5]:
a[:2] # prints elements which have index 0 and 1

array([10, 11])

In [6]:
a[1:3] # prints index element 1 and 2 (ot 3 )

array([11, 12])

#### Negative indices

In [7]:
a

array([10, 11, 12, 13])

In [9]:
"""
elements: 10 11 12 13
index   : -4 -3 -2 -1
"""

a[1:-1]

array([11, 12])

#### Omitting indices

In [10]:
a

array([10, 11, 12, 13])

In [11]:
a[:2] # grab first two elements

array([10, 11])

In [12]:
a[1:] # inclusive 

array([11, 12, 13])

In [13]:
a[-2:] # grab last two elements

array([12, 13])

In [15]:
a[::2] # grab every other element means index 0 2 4 6 ... 

array([10, 12])

In [29]:
arr = np.array([[1, 2, 3, 4, 5, 6],
               [10, 11, 12, 13, 14, 15]])

In [31]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [10, 11, 12, 13, 14, 15]])

In [32]:
arr[0, 3:5]  # row 0, column 3 to 4 

array([4, 5])

In [35]:
"""
return 
2,  3
11, 12
"""
arr[:, 1:3]  # all row, col 1 to 2(index starts at zero) 

array([[ 2,  3],
       [11, 12]])

In [36]:
arr = np.array([[1, 2, 3, 4, 5],
               [11, 12, 13, 14, 15],
               [21, 22, 23, 24, 25],
               [31, 32, 33, 34, 35],
               [41, 42, 43, 44, 45]])

In [37]:
arr

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [39]:
arr[3:, 3:]

array([[34, 35],
       [44, 45]])

In [44]:
# return all the element from 3rd row
arr[2:3, :]

array([[21, 22, 23, 24, 25]])

#### Striding

In [50]:
arr

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [49]:
arr[2::2, ::2]

array([[21, 23, 25],
       [41, 43, 45]])