In [1]:
import numpy as np

In [3]:
a = np.array([10, 11, 12, 13])
a

array([10, 11, 12, 13])

In [4]:
a[:]

array([10, 11, 12, 13])

In [5]:
a[2:] # prints all index elements from 2 

array([12, 13])

In [6]:
a[:2] # prints elements which have index 0 and 1

array([10, 11])

In [7]:
a[1:3] # prints index element 1 and 2 (ot 3 )

array([11, 12])